
name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_BACKEND: your-backend-app-name   # Replace with your backend App Service name
  AZURE_WEBAPP_NAME_FRONTEND: your-frontend-app-name # Replace with your frontend App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install frontend dependencies and build
        run: |
          npm install
          npm run build

      # Deploy Backend
      - name: Deploy to Azure Web App (Backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/backend

      # Deploy Frontend
      - name: Deploy to Azure Web App (Frontend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: ./dist
